# ============================================================
# Servidor HTTP de la app (health, dev console, metrics)
# ============================================================
quarkus.http.port=8080

# ============================================================
# gRPC SERVIDOR \u00e2\u0080\u0094 el evaluador escucha aqui
# Lo usa el CRUD para llamar NotificarConfiguracionCreada
# ============================================================
quarkus.grpc.server.use-separate-server=true
quarkus.grpc.server.host=0.0.0.0
quarkus.grpc.server.port=50051

# ============================================================
# gRPC CLIENTE \u00e2\u0080\u0094 el evaluador llama al CRUD Node
# RPC: ObtenerConfiguracionesActivas
# El nombre "crud-invernadero" se inyecta luego con @GrpcClient
# ============================================================
quarkus.grpc.clients.crud-invernadero.host=localhost
quarkus.grpc.clients.crud-invernadero.port=50052
quarkus.grpc.clients.crud-invernadero.plain-text=true


quarkus.rabbitmq.devservices.enabled=false