# ============================================================
# Servidor HTTP de la app (health, dev console, metrics)
# ============================================================
quarkus.http.port=8080

# ============================================================
# gRPC SERVIDOR \u00e2\u0080\u0094 el evaluador escucha aqui
# Lo usa el CRUD para llamar NotificarConfiguracionCreada
# ============================================================
quarkus.grpc.server.use-separate-server=true
quarkus.grpc.server.host=0.0.0.0
quarkus.grpc.server.port=50051

# ============================================================
# gRPC CLIENTE \u00e2\u0080\u0094 el evaluador llama al CRUD Node
# RPC: ObtenerConfiguracionesActivas
# El nombre "crud-invernadero" se inyecta luego con @GrpcClient
# ============================================================
quarkus.grpc.clients.crud-invernadero.host=localhost
quarkus.grpc.clients.crud-invernadero.port=50052
quarkus.grpc.clients.crud-invernadero.plain-text=true

# ============================================================
# RabbitMQ
# ============================================================
quarkus.rabbitmq.devservices.enabled=false

rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# ============================================================
# Consumer: lecturas
# Escucha lecturas publicadas con routing key lectura.sensor.*
# ============================================================
mp.messaging.incoming.lecturas-in.connector=smallrye-rabbitmq
mp.messaging.incoming.lecturas-in.exchange.name=lecturas.exchange
mp.messaging.incoming.lecturas-in.exchange.type=topic
mp.messaging.incoming.lecturas-in.exchange.durable=true
mp.messaging.incoming.lecturas-in.queue.name=alarm-evaluator.lecturas
mp.messaging.incoming.lecturas-in.queue.durable=true
mp.messaging.incoming.lecturas-in.routing-keys=lectura.sensor.*

# ============================================================
# Publisher: alarmas
# Publica alarmas con routing key alarma.disparada
# ============================================================
mp.messaging.outgoing.alarmas-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.alarmas-out.exchange.name=alarmas.exchange
mp.messaging.outgoing.alarmas-out.exchange.type=topic
mp.messaging.outgoing.alarmas-out.exchange.durable=true
mp.messaging.outgoing.alarmas-out.default-routing-key=alarma.disparada