# ============================================================
# HTTP
# ============================================================

quarkus.http.port=${HTTP_PORT:8085}

# ============================================================
# MONGODB
# ============================================================

quarkus.mongodb.connection-string=${MONGO_URI:mongodb://mongo:27017}
quarkus.mongodb.database=${MONGO_DATABASE:invernadero_db}

# ============================================================
# CORS
# ============================================================

quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:5173}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# ============================================================
# RABBITMQ
# ============================================================

rabbitmq-host=${RABBITMQ_HOST:rabbitmq}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}

# ============================================================
# CONSUMER
# ============================================================

mp.messaging.incoming.sensor-readings.connector=smallrye-rabbitmq

mp.messaging.incoming.sensor-readings.exchange.name=invernadero.events
mp.messaging.incoming.sensor-readings.exchange.type=topic
mp.messaging.incoming.sensor-readings.exchange.durable=true
mp.messaging.incoming.sensor-readings.exchange.auto-delete=false

mp.messaging.incoming.sensor-readings.queue.name=historical.sensor-readings
mp.messaging.incoming.sensor-readings.queue.durable=true

mp.messaging.incoming.sensor-readings.routing-keys=sensor.lectura.registrada

mp.messaging.incoming.sensor-readings.auto-acknowledgement=true