
# --- MONGODB ---
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=invernadero_db

quarkus.http.port=8085

# --- CORS ---
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# --- RABBITMQ ---
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest
# Configuraci\u00f3n del canal que escuchar\u00e1 la cola
mp.messaging.incoming.sensor-readings.connector=smallrye-rabbitmq
mp.messaging.incoming.sensor-readings.exchange.name=invernadero.events
mp.messaging.incoming.sensor-readings.exchange.type=topic
mp.messaging.incoming.sensor-readings.exchange.durable=true
mp.messaging.incoming.sensor-readings.exchange.auto-delete=false
mp.messaging.incoming.sensor-readings.queue.name=historical.sensor-readings
mp.messaging.incoming.sensor-readings.queue.durable=true
mp.messaging.incoming.sensor-readings.routing-keys=sensor.lectura.registrada
mp.messaging.incoming.sensor-readings.auto-acknowledgement=true
