# --- MONGODB ---
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=invernadero_db

# --- RABBITMQ ---
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest
# Configuraci\u00f3n del canal que escuchar\u00e1 la cola
mp.messaging.incoming.sensor-readings.connector=smallrye-rabbitmq
mp.messaging.incoming.sensor-readings.exchange.name=sensor.events.topic
mp.messaging.incoming.sensor-readings.exchange.type=topic
mp.messaging.incoming.sensor-readings.exchange.durable=true
mp.messaging.incoming.sensor-readings.queue.name=sensor-readings-queue
mp.messaging.incoming.sensor-readings.queue.durable=true
mp.messaging.incoming.sensor-readings.routing-keys=sensorReadingEvent
mp.messaging.incoming.sensor-readings.auto-acknowledgement=true