# ============================================================
# HTTP
# ============================================================

quarkus.http.port=${HTTP_PORT:8086}

# ============================================================
# MONGODB
# ============================================================

quarkus.mongodb.connection-string=${MONGO_URI:mongodb://mongo:27017}
quarkus.mongodb.database=${MONGO_DATABASE:invernadero_db}

# ============================================================
# CORS
# ============================================================

quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:5173}

quarkus.http.cors.methods=GET,OPTIONS

quarkus.http.cors.headers=Content-Type,Authorization,X-API-Key

# ============================================================
# JACKSON
# ============================================================

quarkus.jackson.write-dates-as-timestamps=false
quarkus.jackson.serialization-inclusion=non-null