
# --- MONGODB ---
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=invernadero_db

quarkus.http.port=8086

# --- CORS ---
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173
quarkus.http.cors.methods=GET,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,X-API-Key

# --- JACKSON ---
quarkus.jackson.write-dates-as-timestamps=false
quarkus.jackson.serialization-inclusion=non-null
